"""
Hardened Windows atomic filesystem IPC bridge for TheoTown MCP Server.
Provides safe atomic Lua script generation, file replacement with retry backoff,
telemetry reading, and asynchronous job state tracking.
"""

from __future__ import annotations

import contextlib
import json
import os
import tempfile
import time
import uuid
from collections.abc import Sequence
from pathlib import Path
from typing import Any

from theotown_mcp.catalog import DraftCatalog, get_catalog
from theotown_mcp.config import TheoTownConfig, get_config
from theotown_mcp.models import (
    CityTelemetry,
    JobStatus,
    PlanCommand,
    PlanValidationResult,
    parse_commands,
)


def serialize_to_lua(obj: Any) -> str:
    """
    Serializes Python primitives, lists, and dictionaries to valid Lua table syntax.
    Guarantees strict escaping to prevent Lua syntax breakage and code injection.
    """
    if obj is None:
        return "nil"
    if isinstance(obj, bool):
        return "true" if obj else "false"
    if isinstance(obj, (int, float)):
        return str(obj)
    if isinstance(obj, str):
        escaped = (
            obj.replace("\\", "\\\\")
            .replace('"', '\\"')
            .replace("\n", "\\n")
            .replace("\r", "\\r")
            .replace("\t", "\\t")
        )
        return f'"{escaped}"'
    if isinstance(obj, (list, tuple)):
        items = [serialize_to_lua(item) for item in obj]
        return "{ " + ", ".join(items) + " }"
    if isinstance(obj, dict):
        entries: list[str] = []
        for k, v in obj.items():
            key_str = str(k)
            if key_str.isidentifier():
                entries.append(f"{key_str} = {serialize_to_lua(v)}")
            else:
                entries.append(f"[{serialize_to_lua(key_str)}] = {serialize_to_lua(v)}")
        return "{ " + ", ".join(entries) + " }"

    # If it's a Pydantic model
    if hasattr(obj, "model_dump"):
        return serialize_to_lua(obj.model_dump())

    raise TypeError(f"Cannot serialize type {type(obj)} to Lua")


def write_atomic_lua(
    target_file: Path,
    lua_content: str,
    max_retries: int = 5,
    base_delay: float = 0.02,
) -> None:
    """
    Atomically writes Lua script content to target_file on Windows.

    Guarantees:
    - Same volume placement (dir=target_file.parent) preventing [WinError 17]
    - Explicit buffer flush and os.fsync before closing handle (prevents 0-byte files)
    - Handle closure before replace (prevents [WinError 32])
    - Exponential backoff retry loop (absorbs transient file locks from game or AV)
    - Automatic orphan cleanup on failure
    """
    parent = target_file.parent
    parent.mkdir(parents=True, exist_ok=True)

    # Windows atomic replace requires closing handle before MoveFileExW
    temp_file = tempfile.NamedTemporaryFile(  # noqa: SIM115
        mode="w",
        dir=parent,
        prefix="tmp_inbox_",
        suffix=".tmp",
        delete=False,
        encoding="utf-8",
    )

    temp_path = Path(temp_file.name)
    try:
        temp_file.write(lua_content)
        temp_file.flush()
        os.fsync(temp_file.fileno())
        temp_file.close()

        for attempt in range(max_retries):
            try:
                os.replace(temp_path, target_file)
                return
            except (PermissionError, OSError):
                if attempt == max_retries - 1:
                    raise
                time.sleep(base_delay * (2 ** attempt))
    except Exception:
        if temp_path.exists():
            with contextlib.suppress(OSError):
                temp_path.unlink()
        raise


def generate_job_lua(
    job_id: str,
    commands: Sequence[PlanCommand | dict[str, Any]],
    timestamp: float | None = None,
) -> str:
    """Generates the full Lua wrapper payload for inbox.lua."""
    ts = timestamp if timestamp is not None else time.time()
    parsed = parse_commands(commands)
    command_dicts = [cmd.model_dump() for cmd in parsed]

    job_data = {
        "job_id": job_id,
        "timestamp": int(ts),
        "created_at": ts,
        "commands": command_dicts,
    }

    lua_table = serialize_to_lua(job_data)

    return (
        f"-- Auto-generated by theotown-mcp bridge\n"
        f"-- Job ID: {job_id}\n"
        f"local storage = TheoTown.getStorage()\n"
        f"if storage then\n"
        f"    storage.theotown_mcp_pending_job = {lua_table}\n"
        f"end\n"
    )


class TheoTownBridge:
    """Coordinates IPC between Python MCP server and the running TheoTown game."""

    def __init__(
        self,
        config: TheoTownConfig | None = None,
        catalog: DraftCatalog | None = None,
    ) -> None:
        self.config = config or get_config()
        self.catalog = catalog or get_catalog(self.config)
        self.jobs: dict[str, JobStatus] = {}

    def read_telemetry(self) -> CityTelemetry:
        """Reads and parses live city telemetry from telemetry.json."""
        telemetry_file = self.config.telemetry_path
        if not telemetry_file.exists():
            return CityTelemetry(connected=False, last_update=0.0)

        try:
            content = telemetry_file.read_text(encoding="utf-8")
            data = json.loads(content)
            data["connected"] = True
            if "last_updated" in data and "last_update" not in data:
                data["last_update"] = float(data["last_updated"])
            return CityTelemetry.model_validate(data)
        except (OSError, json.JSONDecodeError, ValueError, KeyError):
            return CityTelemetry(connected=False, last_update=0.0)

    def validate_plan(
        self,
        commands: Sequence[PlanCommand | dict[str, Any]],
        dry_run: bool = True,
    ) -> PlanValidationResult:
        """
        Validates a sequence of commands using two-layer validation:
        1. Schema validation (Pydantic model constraints)
        2. Runtime bounds check against city dimensions from telemetry
        """
        errors: list[str] = []
        warnings: list[str] = []
        parsed_cmds: list[PlanCommand] = []

        try:
            parsed_cmds = parse_commands(commands)
        except (ValueError, TypeError, KeyError) as exc:
            errors.append(f"Schema validation error: {exc!s}")
            return PlanValidationResult(
                valid=False,
                errors=errors,
                warnings=warnings,
                estimated_cost=0,
                command_count=len(commands),
                affected_tiles=0,
            )

        telemetry = self.read_telemetry()
        city_w = telemetry.width if telemetry.connected else 128
        city_h = telemetry.height if telemetry.connected else 128

        total_tiles = 0
        for i, cmd in enumerate(parsed_cmds):
            cmd_errors = cmd.check_bounds(city_w, city_h)
            for err in cmd_errors:
                errors.append(f"Command #{i+1} ({cmd.cmd}): {err}")

            if hasattr(cmd, "tile_length"):
                total_tiles += cmd.tile_length
            elif hasattr(cmd, "tile_count"):
                total_tiles += cmd.tile_count
            else:
                total_tiles += 1

        estimated_cost = self.catalog.estimate_total_cost(parsed_cmds)
        if telemetry.connected and telemetry.money < estimated_cost:
            warnings.append(
                f"Estimated cost ({estimated_cost}) exceeds active treasury ({telemetry.money})"
            )

        return PlanValidationResult(
            valid=len(errors) == 0,
            errors=errors,
            warnings=warnings,
            estimated_cost=estimated_cost,
            command_count=len(parsed_cmds),
            affected_tiles=total_tiles,
        )

    def execute_plan(self, commands: Sequence[PlanCommand | dict[str, Any]]) -> JobStatus:
        """
        Submits a construction plan to TheoTown via atomic inbox.lua write.
        Registers the job in local tracking.
        """
        parsed_cmds = parse_commands(commands)
        job_id = f"job_{uuid.uuid4().hex[:12]}"
        now = time.time()

        job = JobStatus(
            job_id=job_id,
            status="pending",
            progress=0.0,
            total_steps=len(parsed_cmds),
            completed_steps=0,
            created_at=now,
            updated_at=now,
        )
        self.jobs[job_id] = job

        # Write atomic Lua payload
        lua_script = generate_job_lua(job_id=job_id, commands=parsed_cmds, timestamp=now)
        write_atomic_lua(self.config.inbox_path, lua_script)

        return job

    def get_job_status(self, job_id: str) -> JobStatus:
        """Retrieves current job status, checking local memory and telemetry."""
        # Check if status file exists in plugin directory first (to capture game updates)
        job_file = self.config.plugin_dir / f"job_{job_id}.json"
        if job_file.exists():
            with contextlib.suppress(OSError, json.JSONDecodeError, KeyError, ValueError):
                data = json.loads(job_file.read_text(encoding="utf-8"))
                status = JobStatus.model_validate(data)
                self.jobs[job_id] = status
                return status

        if job_id in self.jobs:
            return self.jobs[job_id]

        now = time.time()
        return JobStatus(
            job_id=job_id,
            status="failed",
            progress=0.0,
            total_steps=0,
            completed_steps=0,
            created_at=now,
            updated_at=now,
            error=f"Job '{job_id}' not found",
        )

    def cancel_job(self, job_id: str) -> dict[str, Any]:
        """Cancels a pending job."""
        if job_id in self.jobs:
            job = self.jobs[job_id]
            if job.status in ("pending", "running"):
                job.status = "cancelled"
                job.updated_at = time.time()

        # Send cancel payload via inbox.lua
        cancel_lua = (
            f"-- Cancel Job {job_id}\n"
            f"local storage = TheoTown.getStorage()\n"
            f"if storage and storage.theotown_mcp_pending_job and storage.theotown_mcp_pending_job.job_id == '{job_id}' then\n"
            f"    storage.theotown_mcp_pending_job = nil\n"
            f"end\n"
        )
        with contextlib.suppress(OSError):
            write_atomic_lua(self.config.inbox_path, cancel_lua)

        return {"job_id": job_id, "status": "cancelled"}

    def set_speed(self, speed: int) -> dict[str, Any]:
        """Sets game simulation speed (0 to 4)."""
        if speed not in (0, 1, 2, 3, 4):
            raise ValueError("Speed must be an integer between 0 and 4")

        speed_lua = (
            f"-- Set Simulation Speed\n"
            f"if City and City.setSpeed then\n"
            f"    City.setSpeed({speed})\n"
            f"end\n"
        )
        write_atomic_lua(self.config.inbox_path, speed_lua)
        return {"status": "success", "speed": speed}


_global_bridge: TheoTownBridge | None = None


def get_bridge(config: TheoTownConfig | None = None) -> TheoTownBridge:
    """Retrieves or initializes the global TheoTownBridge singleton."""
    global _global_bridge
    if _global_bridge is None:
        _global_bridge = TheoTownBridge(config=config)
    return _global_bridge
